<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->services['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('AppBundle\\Controller\\RegisterController:registerAction' => function () {
    return ${($_ = isset($this->services['service_locator..xkn5k3']) ? $this->services['service_locator..xkn5k3'] : $this->load('getServiceLocator__Xkn5k3Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\SecurityController:loginAction' => function () {
    return ${($_ = isset($this->services['service_locator.ax3ajkk']) ? $this->services['service_locator.ax3ajkk'] : $this->load('getServiceLocator_Ax3ajkkService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\SecurityController:registerAction' => function () {
    return ${($_ = isset($this->services['service_locator.v7pdaat']) ? $this->services['service_locator.v7pdaat'] : $this->load('getServiceLocator_V7pdaatService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\RegisterController::registerAction' => function () {
    return ${($_ = isset($this->services['service_locator..xkn5k3']) ? $this->services['service_locator..xkn5k3'] : $this->load('getServiceLocator__Xkn5k3Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\SecurityController::loginAction' => function () {
    return ${($_ = isset($this->services['service_locator.ax3ajkk']) ? $this->services['service_locator.ax3ajkk'] : $this->load('getServiceLocator_Ax3ajkkService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\SecurityController::registerAction' => function () {
    return ${($_ = isset($this->services['service_locator.v7pdaat']) ? $this->services['service_locator.v7pdaat'] : $this->load('getServiceLocator_V7pdaatService.php')) && false ?: '_'};
})));
