<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK1hl8bf\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK1hl8bf/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerK1hl8bf.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerK1hl8bf\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerK1hl8bf\appDevDebugProjectContainer(array(
    'container.build_hash' => 'K1hl8bf',
    'container.build_id' => '9b48ceb8',
    'container.build_time' => 1524848914,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerK1hl8bf');
