<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXrbpqqo\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXrbpqqo/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXrbpqqo.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXrbpqqo\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerXrbpqqo\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Xrbpqqo',
    'container.build_id' => 'd0f772aa',
    'container.build_time' => 1524846474,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerXrbpqqo');
